Repository ulosino/ulosino, pull requests merged in 2022-05, with the labels that each got.

#185 Implement a minor redesign and many miscellaneous improvements
  components/Loading.tsx
  components/LowBatteryError.tsx
  components/Overlay.tsx
  components/VercelPromotion.tsx
  components/Window.tsx
  components/assistants/PreferenceResetAssistant.tsx
  components/assistants/PreferenceTransferAssistant.tsx
  components/confirmations/DisableUpdateFeaturesConfirmation.tsx
  components/layouts/BrowseLayout.tsx
  components/layouts/ErrorLayout.tsx
  components/layouts/Layout.tsx
  components/layouts/PreferencesLayout.tsx
  components/search/CoreSearchGroup.tsx
  components/search/EmptyState.tsx
  components/search/SearchCategory.tsx
  components/search/SearchDerivedOS.tsx
  components/search/SearchDesktop.tsx
  components/search/SearchPackageManager.tsx
  components/search/SearchPlatform.tsx
  components/search/SearchShell.tsx
  components/search/SearchStartupManager.tsx
  components/search/SearchSummary.tsx
  cypress/integration/DynamicPagePaths.js
  cypress/integration/MainLayoutState.js
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_offline.tsx
  pages/about.tsx
  pages/about/legal.tsx
  pages/about/legal/[slug].tsx
  pages/browse.tsx
  pages/browse/[slug].tsx
  pages/index.tsx
  pages/marketplace/[slug].tsx
  pages/menu.tsx
  pages/preferences.tsx
  pages/preferences/accessibility.tsx
  pages/preferences/advanced.tsx
  pages/preferences/appearance.tsx
  pages/preferences/general.tsx
  pages/preferences/notifications.tsx
  pages/search.tsx
  providers/ApplicationProvider.tsx
  providers/BatteryMonitoringProvider.tsx
  providers/UIThemeProvider.ts
  providers/UpdateProvider.tsx
  public/markdown/about/legal/disclaimers.mdx
  public/markdown/about/legal/license.mdx
  public/markdown/about/legal/privacy.mdx
  public/markdown/about/legal/usage.mdx
Labels: Feature, Public, Source Code

#187 Introduce the Font Assistant
  components/assistants/FontAssistant.tsx
  components/assistants/PreferenceResetAssistant.tsx
  components/layouts/Layout.tsx
  next.config.js
  pages/preferences/accessibility.tsx
  providers/UIThemeProvider.ts
Labels: Feature, Source Code

#188 Deprecate ULOSINO
  README.md
  components/layouts/Layout.tsx
Labels: Source Code
